### ISSUE TITLE
igl.per_corner_normals not found.

### ISSUE THREAD

**Issue by JohanKelyn** [danielepanozzo/gp#1]
It seems that the function igl.per_corner_normals has not been defined in the python bindings. All I can see in the documentation are the following functions: per_edge_normals, per_face_normals, and per_vertex_normals.

Since I am running the code in both C++ and python, I did not find this issue in C++.

**Comment by jiangzhongshi** [comment]
Hi,

`igl.per_corner_normals` should be in the binding as of version `2.2.1`  https://github.com/libigl/libigl-python-bindings/releases/tag/2.2.1

Could you double-check the version installed?

**Comment by budmonde** [comment]
Fyi, if you're looking at the documentation at https://libigl.github.io/libigl-python-bindings/igl_docs/, it's very likely kinda outdated. I've just been looking at the repository source code as documentation. All the functions are in here: https://github.com/libigl/libigl-python-bindings/tree/fdbbf2ca10946b185477b72ab348c306fdf01b24/src (note: this link is at the commit tag for v2.2.1)

**Comment by danielepanozzo** [comment]
Hi, 

I will close this issue for now, please let me know if you are still having problems with igl.per_corner_normals.
