### ISSUE TITLE
Assignment 4 Part III

### ISSUE THREAD

**Issue by liubai01** [danielepanozzo/gp#11]
I try `mp.subplot(.., uv=UV)` in instructions, it looks like that:

![image](https://user-images.githubusercontent.com/10471419/161836178-e1e92dd1-67ce-4469-aad1-f62516cb1015.png)

The requirement is:

![image](https://user-images.githubusercontent.com/10471419/161836365-135e6f87-0094-4c58-96ee-8ff4e09db307.png)

What is the color map here? How could we overlay the gradient map over uv checkerboard/grid?

Thank you.

**Comment by danielepanozzo** [comment]
The rendering you have is ok for the assignment. The rendering below requires to use a transparent grid texture and the color is the ratio of the uv triangle area over the triangle area of the 3D mesh.
