### ISSUE TITLE
Install Problem about Assignment1

### ISSUE THREAD

**Issue by Adora2401** [danielepanozzo/gp#5]
Hi Professor,

When I tried to install the requirements in general instruction, 
`conda install -c conda-forge igl` shows "Solving environment: failed with initial frozen solve. Retrying with flexible solve."
Then I tried to use `conda env create -f environment.yml` directly, it shows  
"Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - zlib==1.2.11=h7795811_1010
  - nodejs==14.7.0=hdde0ff8_0
  - jedi==0.18.0=py38h50d1736_2
  ..."

 I'm not sure how to solve this porblem, the solutions I tried:
1.`conda config --set channel_priority flexible`
2. `conda config --set channel_priority false`
3.  recreate an env and activate it.
But they all not work. So could I use Colab instead of Jupyter Notebook? Or how to solve this problem...

Also, when I used Colab to run the sample code
`meshplot.plot(bunny_v, bunny_f, shading={"wireframe": True})`
It throws “TraitError: The 'shadow' trait of a DirectionalLight instance expected an Uninitialized or a LightShadow, not the str 'IPY_MODEL_[object Object]'.”
Could you please tell me how to solve it? Thanks a lot.

**Comment by danielepanozzo** [comment]
What operating system do you have? Is your conda installation able to install other packages (for example conda install numpy)?

**Comment by Adora2401** [comment]
It‘s Mac m1. Conda could intall other packages.

**Comment by danielepanozzo** [comment]
This is a copy of #6, there will be a fix in a few days.
